# Generated by Django 4.2.4 on 2023-09-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceId',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('faceid', models.TextField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=50)),
            ],
        ),
    ]
