# Generated by Django 4.2.4 on 2023-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0002_faceid_id_alter_faceid_faceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
