# Generated by Django 4.2.4 on 2023-09-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0003_alter_faceid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceid',
            name='id',
        ),
        migrations.AlterField(
            model_name='faceid',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
