# Generated by Django 4.2.4 on 2023-09-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0004_remove_faceid_id_alter_faceid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceid',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faceid',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
