# Generated by Django 4.2.4 on 2023-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0005_faceid_id_alter_faceid_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceid',
            name='faceid',
        ),
        migrations.AddField(
            model_name='faceid',
            name='face_encodings_json',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
