# Generated by Django 4.2.4 on 2023-09-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0007_rename_face_encodings_json_faceid_faceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendees', models.TextField()),
                ('data_time', models.DateTimeField()),
                ('group', models.CharField(max_length=50)),
            ],
        ),
    ]
